<?php
 require_once("Database.php");
 require_once("Page.php");
 require_once("Banner.php");
 require_once("Gallery.php");
 require_once("Qna.php");
 require_once("Contact.php");
 require_once("User.php");
 require_once("Location.php");
 require_once("Status.php");
?>